import TopNav from "@/components/shared/Navbar/TopNav";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
    title: "Transflow",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={rubik.className}>
                <TopNav />
                {children}
            </body>
        </html>
    );
}
